name: CI/CD con Docker

on:
  push:
    branches:
      - main   # se ejecuta cada vez que hagas git push a main
  pull_request:
    branches:
      - main   # también en PR hacia main

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t arago1996/demo-ci-cd:latest .

      - name: Push Docker image
        run: docker push arago1996/demo-ci-cd:latest
